import type { NextPage } from 'next'
import Head from 'next/head'
import BottomBanner from '../components/BottomBanner'
import Navbar from '../components/Navbar'
import OurPackages from '../components/OurPackages'
import PageFooter from '../components/PageFooter'
import Services from '../components/Services'
import TopBanner from '../components/TopBanner'
import styles from '../styles/Home.module.css'
import About from '../components/About'
import Contact from './api/Contact'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>gymIt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main m-0 p-0 w-full md:min-h-screen bg-tail-blue">
        <Navbar />
        <TopBanner />
        <About />
        <Services />
        <BottomBanner />
        <OurPackages />
        <Contact />
        <PageFooter />
        
    
      </main>
    </div>
  )
}

export default Home
